import BuyApp from '@/components/clientarea/BuyApp'
import React from 'react'

export const metadata = {
  title: 'Eloheinu - Buy',
  description: 'Generated by create next app',
}

const Buy = () => {
  return (
    <>
      <BuyApp />
    </>
  )
}

export default Buy