import PropApp from '@/components/clientarea/PropApp'
import React from 'react'

// Property Header goes here
export const metadata = {
  title: 'Eloheinu - Property Details',
  description: 'Generated by create next app',
}

const page = ({ list }) => {
  return (
    <>
      <PropApp list={list} />
    </>
  )
}

export default page