import App from "@/components/clientarea/App";

export const metadata = {
  title: 'Eloheinu Real Estate',
  description: 'Generated by create next app',
}

export default function Page() {

  return (
    <>
      <App />
    </>
  )
}