import Listing from '@/components/panel/listings/Listing'
import Sidebar from '@/components/panel/Sidebar'
import { SidebarProvider } from '@/context/SidebarContext'
import React from 'react'

export const metadata = {
  title: 'Eloheinu - Create Listing',
  description: 'Generated by create next app',
}

const Dashboard = () => {
  return (
    <>
      <SidebarProvider>
        <Sidebar />
        <Listing />
      </SidebarProvider>
    </>
  )
}

export default Dashboard