import Login from '@/components/auth/Login'
import PropNavbar from '@/components/property/PropNavbar'
import React from 'react'

export const metadata = {
  title: 'Eloheinu - Login',
  description: 'Generated by create next app',
}

const SignIn = () => {
  return (
    <>
      <PropNavbar />
      <Login />
    </>
  )
}

export default SignIn