import Sidebar from '@/components/panel/Sidebar'
import Profile from '@/components/user/Profile'
import { SidebarProvider } from '@/context/SidebarContext'
import React from 'react'

export const metadata = {
  title: 'Eloheinu - Dashboard',
  description: 'Generated by create next app',
}

const Dashboard = () => {
  return (
    <>
      <SidebarProvider>
        <Sidebar />
        <Profile />
      </SidebarProvider>
    </>
  )
}

export default Dashboard