import AboutApp from '@/components/clientarea/AboutApp'
import React from 'react'

export const metadata = {
  title: 'Eloheinu - About',
  description: 'Generated by create next app',
}

const About = ({ user }) => {
  return (
    <>
      <AboutApp />
    </>
  )
}

export default About